[package]
name = "rsmath"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rust_decimal = { version = "1.35.0", features = ["maths"] }

[dev-dependencies]
rust_decimal = "1.35.0"
rust_decimal_macros = "1.35.0"
